services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kinobot
    environment:
      - BOT_TOKEN=8136303197:AAH2ivXohIi51V9aRRF2NdGclaLiK4aLKpE
    volumes:
      - ./data:/app/data  # Ma'lumotlarni saqlash uchun jild
    restart: unless-stopped  # Konteyner o'chganda avto-qayta ishga tushadi

volumes:
  data:  # Ma'lumotlarni saqlash uchun nomlangan jild