services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Oriental_bot
    environment:
      - BOT_TOKEN=8245544520:AAHowYT2R1s_DN_4ReV-yks05qKfgsW1h-I
    volumes:
      - ./data:/app/data  # Ma'lumotlarni saqlash uchun jild
    restart: unless-stopped  # Konteyner o'chganda avto-qayta ishga tushadi

volumes:
  data:  # Ma'lumotlarni saqlash uchun nomlangan jild